# Generated by Django 3.2.12 on 2022-04-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptType',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('name', models.CharField(max_length=120, verbose_name='Script Name')),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('filename', models.FileField(upload_to='')),
                ('dependsOn', models.ManyToManyField(null=True, related_name='_scripts_script_dependsOn_+', to='scripts.Script')),
                ('scriptType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.scripttype')),
            ],
        ),
    ]
