# Generated by Django 3.2.12 on 2022-04-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_alter_script_dependson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='dependsOn',
            field=models.ManyToManyField(blank=True, related_name='_scripts_script_dependsOn_+', to='scripts.Script'),
        ),
    ]
