# Generated by Django 3.2.12 on 2022-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_alter_script_dependson'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
    ]
