# Generated by Django 3.2.12 on 2022-05-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_script_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='dependsOn',
            field=models.ManyToManyField(blank=True, to='scripts.Script'),
        ),
    ]
