# Generated by Django 3.2.18 on 2023-03-21 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_alter_script_dependson'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleRole',
            fields=[
                ('name', models.CharField(max_length=120, verbose_name='Role Name')),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('filename', models.FileField(upload_to='')),
                ('version', models.BigIntegerField(default=1)),
                ('dependsOn', models.ManyToManyField(blank=True, to='scripts.AnsibleRole')),
                ('scriptType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.scripttype', verbose_name='Role Type')),
            ],
        ),
        migrations.CreateModel(
            name='AnsiblePlaybook',
            fields=[
                ('name', models.CharField(max_length=120, verbose_name='Playbook Name')),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('filename', models.FileField(upload_to='')),
                ('version', models.BigIntegerField(default=1)),
                ('dependsOn', models.ManyToManyField(blank=True, to='scripts.AnsiblePlaybook')),
                ('scriptType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.scripttype', verbose_name='Playbook Type')),
            ],
        ),
    ]
