# Generated by Django 3.2.18 on 2023-03-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_ansibleplaybook_ansiblerole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ansibleplaybook',
            options={'verbose_name': 'Ansible Playbook'},
        ),
        migrations.AlterModelOptions(
            name='ansiblerole',
            options={'verbose_name': 'Ansible Role'},
        ),
    ]
