# Generated by Django 3.2.18 on 2023-04-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_ansiblerole_roleurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansiblerole',
            name='filename',
        ),
    ]
