# Generated by Django 3.2.18 on 2023-05-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0010_alter_ansiblerole_roleurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleCollection',
            fields=[
                ('name', models.CharField(max_length=120, verbose_name='Collection Name')),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('collectionurl', models.CharField(help_text="The Ansible Galaxy Collection descriptor.  See the 'ansible-galaxy' command for help.", max_length=2048, verbose_name='Collection URL')),
                ('version', models.BigIntegerField(default=1)),
                ('dependsOn', models.ManyToManyField(blank=True, to='scripts.AnsibleCollection')),
                ('scriptType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.scripttype', verbose_name='Collection Type')),
            ],
            options={
                'verbose_name': 'Ansible Collection',
            },
        ),
    ]
