# Generated by Django 3.2.18 on 2025-06-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0011_ansiblecollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('name', models.CharField(max_length=120, verbose_name='File Name')),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('filename', models.FileField(upload_to='')),
                ('version', models.BigIntegerField(default=1)),
            ],
        ),
    ]
