# Generated by Django 3.2.18 on 2025-11-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0012_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
