# Generated by Django 3.2.12 on 2022-04-25 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModule',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('active', models.IntegerField(default=0)),
                ('slug', models.SlugField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Module ID')),
            ],
            options={
                'verbose_name': 'Job Module',
            },
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Job Status',
            },
        ),
        migrations.CreateModel(
            name='JobServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.GenericIPAddressField()),
                ('heartbeat_time', models.DateTimeField(auto_now=True, verbose_name='Last Heart Beat')),
                ('jobmodules', models.ManyToManyField(to='jobqueue.JobModule', verbose_name='Handled Job Modules')),
            ],
            options={
                'verbose_name': 'Job Server',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('return_code', models.IntegerField(blank=True, null=True, verbose_name='Return Code')),
                ('params', models.JSONField(default=dict, null=True, verbose_name='Job Parameters')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobqueue.jobmodule')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobqueue.jobstatus')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
