# Generated by Django 3.2.12 on 2022-04-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Job Module',
            },
        ),
        migrations.CreateModel(
            name='JobServers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.GenericIPAddressField()),
                ('heartbeat_time', models.DateTimeField(auto_now=True, verbose_name='Last Heart Beat')),
            ],
            options={
                'verbose_name': 'Job Server',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('return_code', models.IntegerField(blank=True, null=True, verbose_name='Return Code')),
                ('params', models.JSONField(blank=True, null=True, verbose_name='Job Parameters')),
                ('status', models.IntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobqueue.jobmodules')),
            ],
            options={
                'verbose_name': 'Job Queue',
                'verbose_name_plural': 'Job Queue',
            },
        ),
    ]
