# Generated by Django 3.2.12 on 2022-04-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobserver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobqueue.jobserver'),
        ),
    ]
