# Generated by Django 3.2.12 on 2022-04-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodules',
            name='jobtype',
            field=models.IntegerField(default=0, verbose_name='Job Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobservers',
            name='jobmodules',
            field=models.ManyToManyField(to='jobqueue.JobModules', verbose_name='Handled Modules'),
        ),
    ]
