# Generated by Django 3.2.12 on 2022-04-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0002_auto_20220402_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodules',
            name='jobtype',
        ),
        migrations.AddField(
            model_name='jobmodules',
            name='slug',
            field=models.SlugField(default='test', editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobservers',
            name='jobmodules',
            field=models.ManyToManyField(to='jobqueue.JobModules', verbose_name='Handled Job Modules'),
        ),
    ]
