# Generated by Django 3.2.12 on 2022-04-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0002_job_jobserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobserver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobqueue.jobserver', verbose_name='Assigned Job Server'),
        ),
        migrations.AlterField(
            model_name='jobserver',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
