# Generated by Django 3.2.12 on 2022-04-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0003_auto_20220406_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
        migrations.RenameModel(
            old_name='JobModules',
            new_name='JobModule',
        ),
        migrations.RenameModel(
            old_name='JobServers',
            new_name='JobServer',
        ),
    ]
