# Generated by Django 3.2.12 on 2022-04-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0005_jobstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobqueue.jobstatus'),
        ),
    ]
