# Generated by Django 3.2.13 on 2022-06-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0005_alter_jobserver_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobserver',
            name='one_minute_load',
            field=models.IntegerField(default=0, null=True, verbose_name='1 Minute Load Avg.'),
        ),
    ]
