# Generated by Django 3.2.12 on 2022-04-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0006_alter_job_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
