# Generated by Django 3.2.13 on 2022-07-01 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0012_auto_20220623_1400'),
        ('jobqueue', '0006_jobserver_one_minute_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobserver',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.network'),
        ),
    ]
