# Generated by Django 3.2.12 on 2022-04-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0007_alter_job_options'),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='jobstatus',
            options={'verbose_name': 'Job Status'},
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobqueue.jobstatus'),
        ),
    ]
