# Generated by Django 3.2.12 on 2022-04-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0008_auto_20220407_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobserver',
            name='jobmodules',
        ),
        migrations.RemoveField(
            model_name='job',
            name='module',
        ),
        migrations.RemoveField(
            model_name='jobmodule',
            name='id',
        ),
        migrations.AlterField(
            model_name='jobmodule',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Module ID'),
        ),
    ]
