# Generated by Django 3.2.12 on 2022-04-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0009_auto_20220407_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobserver',
            name='jobmodules',
            field=models.ManyToManyField(to='jobqueue.JobModule', verbose_name='Handled Job Modules'),
        ),
    ]
