# Generated by Django 3.2.13 on 2022-08-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskpartition',
            name='disklayout',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='disklayouts.disklayout', verbose_name='Associated Layout'),
            preserve_default=False,
        ),
    ]
