# Generated by Django 3.2.13 on 2022-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0002_diskpartition_disklayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disklayout',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
