# Generated by Django 3.2.13 on 2022-08-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0025_remove_system_bootdisk'),
        ('disklayouts', '0003_alter_disklayout_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='disklayout',
            name='system',
            field=models.ManyToManyField(blank=True, to='systems.System'),
        ),
    ]
