# Generated by Django 3.2.13 on 2022-08-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0026_system_disks'),
        ('disklayouts', '0005_alter_disklayout_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disklayout',
            name='system',
        ),
        migrations.AddField(
            model_name='disklayout',
            name='systems',
            field=models.ManyToManyField(blank=True, to='systems.System'),
        ),
    ]
