# Generated by Django 3.2.13 on 2022-08-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0007_auto_20220805_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='disklayout',
            name='type',
            field=models.CharField(choices=[('scsi', 'SCSI Disk'), ('nvme', 'NVMe'), ('mdrd', 'Sofware RAID')], default='scsi', max_length=4),
        ),
        migrations.AddField(
            model_name='diskpartition',
            name='bootable',
            field=models.BooleanField(default=False, verbose_name='Booable Partition?'),
        ),
    ]
