# Generated by Django 3.2.13 on 2022-08-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0008_auto_20220812_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disklayout',
            old_name='type',
            new_name='dtype',
        ),
    ]
