# Generated by Django 3.2.13 on 2022-08-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0010_auto_20220815_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskpartition',
            name='mount',
            field=models.CharField(help_text="The directory this partition will mount to or 'raid' if it is a Software RAID member.", max_length=4096, verbose_name='Mount Point'),
        ),
        migrations.CreateModel(
            name='RaidLayout',
            fields=[
                ('disklayout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='disklayouts.disklayout')),
                ('partion_members', models.ManyToManyField(blank=True, to='disklayouts.DiskPartition')),
            ],
            bases=('disklayouts.disklayout',),
        ),
    ]
