# Generated by Django 3.2.13 on 2022-08-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0011_auto_20220819_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskpartition',
            name='partnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disklayout',
            name='dtype',
            field=models.CharField(choices=[('scsi', 'SCSI Disk'), ('nvme', 'NVMe'), ('mdrd', 'Sofware RAID')], default='mdrd', max_length=4, verbose_name='Disk Type'),
        ),
    ]
