# Generated by Django 3.2.13 on 2022-08-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0012_auto_20220822_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskpartition',
            name='partnum',
            field=models.IntegerField(default=0, verbose_name='Part. Number'),
        ),
    ]
