# Generated by Django 3.2.13 on 2022-08-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0014_alter_diskpartition_partnum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disklayout',
            options={'verbose_name': 'Physical Disk Layout'},
        ),
        migrations.AlterModelOptions(
            name='raidlayout',
            options={'verbose_name': 'Software RAID Layout'},
        ),
        migrations.AddField(
            model_name='raidlayout',
            name='filesystem',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='disklayout',
            name='dtype',
            field=models.CharField(choices=[('scsi', 'SCSI Disk'), ('nvme', 'NVMe'), ('mdrd', 'Software RAID')], default='mdrd', max_length=4, verbose_name='Disk Type'),
        ),
    ]
