# Generated by Django 3.2.13 on 2022-08-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0015_auto_20220823_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskpartition',
            name='partnum',
            field=models.IntegerField(default=0, verbose_name='Part. Number'),
        ),
    ]
