# Generated by Django 3.2.13 on 2022-08-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0019_auto_20220823_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raidlayout',
            old_name='partion_members',
            new_name='partition_members',
        ),
    ]
