# Generated by Django 3.2.13 on 2022-08-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0020_rename_partion_members_raidlayout_partition_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidlayout',
            name='raidlevel',
            field=models.CharField(choices=[('raid0', 'RAID 0'), ('raid1', 'RAID 1'), ('raid5', 'RAID 5'), ('raid6', 'RAID 6')], default='raid0', max_length=6, verbose_name='RAID Level'),
        ),
    ]
