# Generated by Django 3.2.13 on 2022-09-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0022_raidlayout_mount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskpartition',
            name='bootable',
            field=models.BooleanField(default=False, verbose_name='Bootable Partition?'),
        ),
    ]
