# Generated by Django 3.2.22 on 2023-12-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0023_alter_diskpartition_bootable'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskpartition',
            name='format',
            field=models.BooleanField(default=True, verbose_name='Format?'),
        ),
    ]
