# Generated by Django 3.2.23 on 2024-01-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0024_diskpartition_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskpartition',
            name='format',
            field=models.BooleanField(default=True, help_text='If checked, the partition will always be wiped. If unchecked, the partition will only be wiped if no filesystem is detected.', verbose_name='Force Format?'),
        ),
    ]
