# Generated by Django 3.2.23 on 2024-01-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0025_alter_diskpartition_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskpartition',
            name='filesystem',
            field=models.CharField(max_length=255, verbose_name='Filesystem'),
        ),
    ]
