# Generated by Django 3.2.12 on 2022-04-25 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSDistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('config_params', models.TextField(blank=True, default='-- # None', null=True, verbose_name='Configuration\nParameters')),
                ('install_kernel_cmdline', models.CharField(blank=True, help_text='Options to pass to the install kernel', max_length=4096, null=True)),
            ],
            options={
                'verbose_name': 'OS Distrubution',
                'verbose_name_plural': 'OS Distrubutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OSRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('repo_package_url', models.CharField(max_length=2048, verbose_name='Repo Package URL')),
                ('osdistro', models.ManyToManyField(blank=True, to='osmanagement.OSDistro', verbose_name='OS Distrubution')),
            ],
            options={
                'verbose_name': 'OS Repository',
                'verbose_name_plural': 'OS Repositories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='osdistro',
            name='baserepo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osmanagement.osrepo', verbose_name='OS Base Repository'),
        ),
        migrations.AddField(
            model_name='osdistro',
            name='osrepos',
            field=models.ManyToManyField(blank=True, related_name='_osmanagement_osdistro_osrepos_+', to='osmanagement.OSRepo', verbose_name='OS Repositories'),
        ),
    ]
