# Generated by Django 3.2.12 on 2022-04-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSDistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'OS Distrubution',
                'verbose_name_plural': 'OS Distrubutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OSRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=2048)),
                ('osdistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osmanagement.osdistro')),
            ],
            options={
                'verbose_name': 'OS Repository',
                'verbose_name_plural': 'OS Repositories',
                'ordering': ['name'],
            },
        ),
    ]
