# Generated by Django 3.2.12 on 2022-04-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osrepo',
            name='url',
        ),
        migrations.AddField(
            model_name='osrepo',
            name='repo_package_url',
            field=models.CharField(default='', max_length=2048, verbose_name='Repo Package URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='osrepo',
            name='osdistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osmanagement.osdistro', verbose_name='OS Distro'),
        ),
    ]
