# Generated by Django 3.2.12 on 2022-04-26 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osdistro',
            name='baserepo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseRepository', to='osmanagement.osrepo', verbose_name='OS Base Repository'),
        ),
    ]
