# Generated by Django 3.2.12 on 2022-04-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0002_auto_20220401_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdistro',
            name='osrepos',
            field=models.ManyToManyField(blank=True, related_name='_osmanagement_osdistro_osrepos_+', to='osmanagement.OSRepo', verbose_name='OS Distrubutions'),
        ),
        migrations.RemoveField(
            model_name='osrepo',
            name='osdistro',
        ),
        migrations.AddField(
            model_name='osrepo',
            name='osdistro',
            field=models.ManyToManyField(blank=True, to='osmanagement.OSDistro', verbose_name='OS Distrubution'),
        ),
    ]
