# Generated by Django 3.2.12 on 2022-04-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_alter_script_dependson'),
        ('osmanagement', '0002_alter_osdistro_baserepo'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdistro',
            name='scripts',
            field=models.ManyToManyField(to='scripts.Script'),
        ),
    ]
