# Generated by Django 3.2.12 on 2022-04-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0003_auto_20220401_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='osrepo',
            name='config_params',
            field=models.TextField(default='-- # None'),
        ),
        migrations.AddField(
            model_name='osrepo',
            name='install_kernel_cmdline',
            field=models.CharField(blank=True, help_text='Options to pass to the install kernel', max_length=4096, null=True),
        ),
    ]
