# Generated by Django 3.2.13 on 2022-06-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0004_alter_osdistro_scripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osdistro',
            name='config_params',
            field=models.TextField(blank=True, default='# None', null=True, verbose_name='Configuration\nParameters'),
        ),
    ]
