# Generated by Django 3.2.12 on 2022-04-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0005_auto_20220401_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osdistro',
            name='config_params',
            field=models.TextField(blank=True, default='-- # None', null=True),
        ),
    ]
