# Generated by Django 3.2.13 on 2022-06-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0006_auto_20220623_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osdistro',
            name='install_kernel_cmdline',
            field=models.CharField(default='', help_text='Options to pass to the install kernel', max_length=4096),
        ),
    ]
