# Generated by Django 3.2.12 on 2022-04-01 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0007_alter_osdistro_config_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdistro',
            name='baserepo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osmanagement.osrepo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='osdistro',
            name='osrepos',
            field=models.ManyToManyField(blank=True, related_name='_osmanagement_osdistro_osrepos_+', to='osmanagement.OSRepo', verbose_name='OS Repositories'),
        ),
    ]
