# Generated by Django 3.2.13 on 2022-07-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0008_alter_jobserver_one_minute_load'),
        ('osmanagement', '0007_alter_osdistro_install_kernel_cmdline'),
    ]

    operations = [
        migrations.AddField(
            model_name='osrepo',
            name='hosted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobqueue.jobserver', verbose_name='Hosted by'),
        ),
        migrations.AddField(
            model_name='osrepo',
            name='managed',
            field=models.BooleanField(default=False, help_text='Should mProv download and manage this repository?', verbose_name='mProv Managed?'),
        ),
        migrations.AddField(
            model_name='osrepo',
            name='update',
            field=models.BooleanField(default=False, help_text='Should we update a managed repository?', verbose_name='Update Repository?'),
        ),
    ]
