# Generated by Django 3.2.12 on 2022-04-01 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0008_auto_20220401_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osdistro',
            name='baserepo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osmanagement.osrepo', verbose_name='OS Base Repository'),
        ),
    ]
