# Generated by Django 3.2.13 on 2022-07-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0008_alter_jobserver_one_minute_load'),
        ('osmanagement', '0009_remove_osrepo_hosted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='osrepo',
            name='hosted_by',
            field=models.ManyToManyField(blank=True, null=True, to='jobqueue.JobServer', verbose_name='Hosted by'),
        ),
    ]
