# Generated by Django 3.2.12 on 2022-04-01 20:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0009_alter_osdistro_baserepo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osdistro',
            name='config_params',
            field=ckeditor.fields.RichTextField(blank=True, default='-- # None', null=True, verbose_name='Configuration\nParameters'),
        ),
    ]
