# Generated by Django 3.2.13 on 2022-07-19 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0011_alter_osrepo_hosted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSType',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='osrepo',
            name='ostype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osmanagement.ostype'),
        ),
    ]
