# Generated by Django 3.2.13 on 2022-07-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0013_alter_osrepo_ostype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osdistro',
            name='install_kernel_cmdline',
            field=models.CharField(blank=True, default='', help_text='Options to pass to the install kernel', max_length=4096),
        ),
    ]
