# Generated by Django 3.2.13 on 2022-07-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0014_alter_osdistro_install_kernel_cmdline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osrepo',
            name='osdistro',
        ),
    ]
