# Generated by Django 3.2.15 on 2022-10-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0016_alter_osdistro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='osrepo',
            name='version',
            field=models.BigIntegerField(default=1, help_text='Local version of the repository, if mProv Managed.', verbose_name='Repository Local Version'),
        ),
    ]
