# Generated by Django 3.2.18 on 2023-04-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_ansiblerole_roleurl'),
        ('osmanagement', '0018_osdistro_ansibleplaybooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osdistro',
            name='ansibleplaybooks',
            field=models.ManyToManyField(blank=True, to='scripts.AnsiblePlaybook', verbose_name='Ansible Playbooks'),
        ),
    ]
