# Generated by Django 3.2.18 on 2023-05-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0011_ansiblecollection'),
        ('osmanagement', '0020_osdistro_ansibleroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdistro',
            name='ansiblecollections',
            field=models.ManyToManyField(blank=True, to='scripts.AnsibleCollection', verbose_name='Ansible Collections'),
        ),
    ]
