# Generated by Django 3.2.23 on 2023-11-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0021_osdistro_ansiblecollections'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdistro',
            name='rootpw',
            field=models.CharField(blank=True, default='changeme', help_text='Root Password for the image', max_length=255, verbose_name='Root Password'),
        ),
        migrations.AddField(
            model_name='osdistro',
            name='rootsshkeys',
            field=models.TextField(blank=True, help_text='Keys to add to the authorized keys file.', verbose_name='Root SSH Keys'),
        ),
    ]
