# Generated by Django 3.2.23 on 2024-01-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0022_auto_20231116_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdistro',
            name='baseurl',
            field=models.CharField(default='https://download.rockylinux.org/pub/rocky/8/', max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='osdistro',
            name='managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osdistro',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
