# Generated by Django 3.2.23 on 2024-01-18 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0023_auto_20240116_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdistro',
            name='distArch',
            field=models.CharField(choices=[('x86_64', 'x86_64'), ('aarch64', 'aarch64'), ('ppc64le', 'ppc64le'), ('s390x', 's390x')], default='x86_64', max_length=400),
        ),
        migrations.AddField(
            model_name='osdistro',
            name='distType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osmanagement.ostype', verbose_name='OS Type'),
        ),
    ]
