# Generated by Django 3.2.23 on 2024-01-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0025_alter_osdistro_baserepo'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdistro',
            name='extrarepos',
            field=models.ManyToManyField(blank=True, related_name='_osmanagement_osdistro_extrarepos_+', to='osmanagement.OSRepo', verbose_name='Extra Repositories'),
        ),
    ]
