# Generated by Django 4.2.20 on 2025-05-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0026_osdistro_extrarepos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osdistro',
            name='extrarepos',
            field=models.ManyToManyField(blank=True, related_name='+', to='osmanagement.osrepo', verbose_name='Extra Repositories'),
        ),
        migrations.AlterField(
            model_name='osdistro',
            name='osrepos',
            field=models.ManyToManyField(blank=True, related_name='+', to='osmanagement.osrepo', verbose_name='OS Repositories'),
        ),
    ]
