# Generated by Django 3.2.12 on 2022-04-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_network_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
