# Generated by Django 3.2.12 on 2022-03-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_switch_switchport'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='mgmt_mac',
            field=models.CharField(default='de:ad:be:ef:00:01', max_length=100),
            preserve_default=False,
        ),
    ]
