# Generated by Django 3.2.12 on 2022-03-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_switch_mgmt_mac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switch',
            options={'verbose_name': 'Switch', 'verbose_name_plural': 'Switches'},
        ),
    ]
