# Generated by Django 3.2.12 on 2022-04-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0004_auto_20220430_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='dhcpend',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='dhcpstart',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
