# Generated by Django 3.2.12 on 2022-03-30 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('networks', '0004_alter_switch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='net_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.networktype', verbose_name='Network Type'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='domainname',
            field=models.CharField(max_length=255, verbose_name='Domain Name'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='hostname',
            field=models.CharField(max_length=255, verbose_name='Host Name'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='mgmt_ip',
            field=models.GenericIPAddressField(verbose_name='Management IP'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='mgmt_mac',
            field=models.CharField(max_length=100, verbose_name='Management MAC'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
