# Generated by Django 3.2.12 on 2022-04-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0005_auto_20220330_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networktype',
            options={'verbose_name': 'Network Type'},
        ),
        migrations.AlterModelOptions(
            name='switchport',
            options={'verbose_name': 'Switch Port'},
        ),
    ]
