# Generated by Django 3.2.12 on 2022-05-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0006_remove_switch_domainname'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='gateway',
            field=models.GenericIPAddressField(default='172.16.1.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='nameserver1',
            field=models.GenericIPAddressField(default='172.16.1.1'),
            preserve_default=False,
        ),
    ]
