# Generated by Django 3.2.12 on 2022-04-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0006_auto_20220401_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='netmask',
            field=models.IntegerField(default=32, verbose_name=range(1, 32)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='subnet',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='network',
            name='vlan',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
