# Generated by Django 3.2.13 on 2022-05-04 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('networks', '0007_auto_20220504_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(1), to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='networks.network', verbose_name='Management\nNetwork'),
        ),
        migrations.RemoveField(
            model_name='switchport',
            name='networks',
        ),
        migrations.AddField(
            model_name='switchport',
            name='networks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='networks.network', verbose_name='Network'),
        ),
    ]
