# Generated by Django 3.2.13 on 2022-05-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0008_auto_20220504_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='network',
            name='gateway',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='nameserver1',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Network ID'),
        ),
    ]
