# Generated by Django 3.2.12 on 2022-04-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0008_auto_20220401_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchport',
            name='networks',
            field=models.ManyToManyField(to='networks.Network', verbose_name='Networks'),
        ),
    ]
