# Generated by Django 3.2.12 on 2022-04-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0009_alter_switchport_networks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='vlan',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
