# Generated by Django 3.2.13 on 2022-06-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0009_auto_20220519_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='networktype',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Network Type ID'),
        ),
    ]
