# Generated by Django 3.2.13 on 2022-06-18 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0010_networktype_slug'),
    ]

    operations = [

        migrations.AlterField(
            model_name='networktype',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='Network Type ID'),
        ),
    ]
