# Generated by Django 3.2.16 on 2022-11-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0012_auto_20220623_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.network', verbose_name='Management\nNetwork'),
        ),
    ]
