# Generated by Django 3.2.16 on 2022-11-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0013_alter_switch_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchport',
            name='networks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.network', verbose_name='Network'),
        ),
    ]
