# Generated by Django 3.2.23 on 2024-01-23 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0014_alter_switchport_networks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 3, 16, 43, 725732, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 3, 16, 43, 725788, tzinfo=utc), verbose_name='Last Updated'),
        ),
    ]
