# Generated by Django 3.2.12 on 2022-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemimage',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Image Name'),
        ),
    ]
