# Generated by Django 3.2.12 on 2022-03-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extra_fields', models.TextField(blank=True, default='-- # Inherit')),
                ('parent_id', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'System Group',
                'verbose_name_plural': 'System Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['hostname'], 'verbose_name': 'System Inventory', 'verbose_name_plural': 'System Inventory'},
        ),
        migrations.AddField(
            model_name='system',
            name='systemgroups',
            field=models.ManyToManyField(to='systems.SystemGroup'),
        ),
    ]
