# Generated by Django 3.2.12 on 2022-04-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0002_alter_osdistro_baserepo'),
        ('systems', '0002_alter_systemimage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemgroup',
            old_name='conf_params',
            new_name='config_params',
        ),
        migrations.RenameField(
            model_name='systemimage',
            old_name='config_parameters',
            new_name='config_params',
        ),
        migrations.AlterField(
            model_name='systemimage',
            name='osdistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distro', to='osmanagement.osdistro', verbose_name='OS Distrubution'),
        ),
    ]
