# Generated by Django 3.2.12 on 2022-03-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20220330_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemgroup',
            name='extra_fields',
            field=models.TextField(blank=True, default='-- # Inherit from OS', verbose_name='Extra Fields'),
        ),
    ]
