# Generated by Django 3.2.12 on 2022-04-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20220426_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='config_parameters',
            new_name='config_params',
        ),
    ]
