# Generated by Django 3.2.12 on 2022-03-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_alter_systemgroup_extra_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['hostname'], 'verbose_name': 'Systems', 'verbose_name_plural': 'Systems'},
        ),
    ]
