# Generated by Django 3.2.12 on 2022-04-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_alter_script_dependson'),
        ('systems', '0005_auto_20220429_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='scripts',
            field=models.ManyToManyField(blank=True, to='scripts.Script'),
        ),
        migrations.AlterField(
            model_name='systemgroup',
            name='scripts',
            field=models.ManyToManyField(blank=True, to='scripts.Script'),
        ),
    ]
