# Generated by Django 3.2.12 on 2022-04-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0006_auto_20220401_1351'),
        ('systems', '0005_alter_system_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemgroup',
            name='extra_fields',
        ),
        migrations.AddField(
            model_name='systemgroup',
            name='conf_params',
            field=models.TextField(blank=True, default='-- # Inherit from OS', verbose_name='Configuration Parameters'),
        ),
        migrations.AlterField(
            model_name='networkinterface',
            name='switch_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.switchport', verbose_name='Switch Port'),
        ),
    ]
