# Generated by Django 3.2.12 on 2022-04-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_alter_script_dependson'),
        ('systems', '0006_auto_20220429_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemimage',
            name='scripts',
            field=models.ManyToManyField(blank=True, to='scripts.Script'),
        ),
    ]
