# Generated by Django 3.2.12 on 2022-04-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0003_auto_20220401_1430'),
        ('systems', '0006_auto_20220401_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='osdistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osmanagement.osdistro'),
        ),
        migrations.AddField(
            model_name='system',
            name='osrepos',
            field=models.ManyToManyField(blank=True, to='osmanagement.OSRepo'),
        ),
    ]
