# Generated by Django 3.2.12 on 2022-04-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0004_auto_20220401_1814'),
        ('systems', '0007_auto_20220401_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='osdistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osmanagement.osdistro', verbose_name='OS Distrubution'),
        ),
        migrations.AlterField(
            model_name='system',
            name='osrepos',
            field=models.ManyToManyField(blank=True, to='osmanagement.OSRepo', verbose_name='OS Repositories'),
        ),
        migrations.AlterField(
            model_name='system',
            name='systemgroups',
            field=models.ManyToManyField(blank=True, to='systems.SystemGroup', verbose_name='System Groups'),
        ),
    ]
