# Generated by Django 3.2.12 on 2022-05-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_systemimage_scripts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkinterface',
            name='domainname',
        ),
        migrations.RemoveField(
            model_name='system',
            name='domainname',
        ),
    ]
