# Generated by Django 3.2.12 on 2022-05-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_auto_20220502_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterface',
            name='mac',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MAC Address'),
        ),
    ]
