# Generated by Django 3.2.12 on 2022-04-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_auto_20220401_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='config_parameters',
            field=models.TextField(default='-- #Inherit from System Group or Distrubtion.'),
        ),
    ]
