# Generated by Django 3.2.12 on 2022-04-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_system_config_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='config_parameters',
            field=models.TextField(default='-- #Inherit from System Group or Distrubtion.', verbose_name='Configuration\nParameters'),
        ),
    ]
