# Generated by Django 3.2.12 on 2022-05-02 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_alter_networkinterface_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='systemimage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.systemimage'),
        ),
    ]
