# Generated by Django 3.2.13 on 2022-05-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0008_auto_20220504_1844'),
        ('systems', '0011_auto_20220502_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='IP Address ')),
                ('mac', models.CharField(blank=True, max_length=100, null=True, verbose_name='MAC Address')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='BMC User')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='BMC Password')),
                ('switch_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.switchport', verbose_name='Switch Port')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.system')),
            ],
            options={
                'verbose_name': 'System BMC',
                'verbose_name_plural': 'System BMCs',
            },
        ),
    ]
