# Generated by Django 3.2.12 on 2022-04-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0011_auto_20220401_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='hostname',
            field=models.CharField(default='mgmt', max_length=255),
            preserve_default=False,
        ),
    ]
