# Generated by Django 3.2.12 on 2022-04-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0012_networkinterface_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='domainname',
            field=models.CharField(default='test.local', max_length=255),
            preserve_default=False,
        ),
    ]
