# Generated by Django 3.2.12 on 2022-04-16 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0011_alter_osdistro_config_params'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systems', '0013_networkinterface_domainname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Image Name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Lasted Updated')),
                ('config_parameters', models.TextField(blank=True, default='-- #Inherit from System Group or Distrubtion.', null=True, verbose_name='Configuration\nParameters')),
                ('created_by', models.ForeignKey(on_delete=models.SET(1), to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('osdistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osmanagement.osdistro', verbose_name='OS Distrubution')),
                ('osrepos', models.ManyToManyField(blank=True, to='osmanagement.OSRepo', verbose_name='OS Repositories')),
                ('systemgroups', models.ManyToManyField(blank=True, to='systems.SystemGroup', verbose_name='System Groups')),
            ],
            options={
                'verbose_name': 'System Image',
                'ordering': ['name'],
            },
        ),
    ]
