# Generated by Django 3.2.13 on 2022-05-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0013_auto_20220505_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterface',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Iface. Name'),
        ),
    ]
