# Generated by Django 3.2.13 on 2022-05-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0014_alter_networkinterface_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='bootable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
