# Generated by Django 3.2.12 on 2022-04-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0014_systemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemimage',
            name='needs_rebuild',
            field=models.BooleanField(default=True),
        ),
    ]
