# Generated by Django 3.2.12 on 2022-04-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0015_systemimage_needs_rebuild'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemimage',
            name='version',
            field=models.BigIntegerField(default=1, verbose_name='Image Version'),
        ),
        migrations.AlterField(
            model_name='systemimage',
            name='needs_rebuild',
            field=models.BooleanField(default=True, verbose_name='Rebuild Image?'),
        ),
    ]
