# Generated by Django 3.2.12 on 2022-04-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0012_job_module'),
        ('systems', '0016_auto_20220420_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemimage',
            name='jobservers',
            field=models.ManyToManyField(blank=True, to='jobqueue.JobServer', verbose_name='Hosted By'),
        ),
    ]
