# Generated by Django 3.2.13 on 2022-05-17 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0008_auto_20220504_1844'),
        ('systems', '0016_alter_networkinterface_switch_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterface',
            name='switch_port',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.switchport', verbose_name='Switch Port'),
        ),
    ]
