# Generated by Django 3.2.13 on 2022-06-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0017_alter_networkinterface_switch_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='config_params',
            field=models.TextField(blank=True, default='#Inherit from System Group or Distrubtion.', null=True, verbose_name='Configuration\nParameters'),
        ),
        migrations.AlterField(
            model_name='systemgroup',
            name='config_params',
            field=models.TextField(blank=True, default='# Inherit from OS', verbose_name='Configuration Parameters'),
        ),
    ]
