# Generated by Django 3.2.13 on 2022-06-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0018_auto_20220623_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='config_params',
            field=models.TextField(blank=True, default='# Inherit from System Group or Distrubtion.', null=True, verbose_name='Configuration\nParameters'),
        ),
        migrations.AlterField(
            model_name='systemimage',
            name='config_params',
            field=models.TextField(blank=True, default='# Inherit from System Group or Distrubtion.', null=True, verbose_name='Configuration\nParameters'),
        ),
    ]
