# Generated by Django 3.2.13 on 2022-08-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0019_auto_20220623_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModel',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Model Name')),
                ('vendor', models.CharField(max_length=255, verbose_name='Vendor Name')),
            ],
        ),
        migrations.AlterField(
            model_name='system',
            name='systemimage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.systemimage', verbose_name='System Image'),
        ),
        migrations.AddField(
            model_name='system',
            name='systemmodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.systemmodel', verbose_name='System Model'),
        ),
    ]
