# Generated by Django 3.2.13 on 2022-08-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0020_auto_20220801_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmodel',
            options={'verbose_name': 'System Models', 'verbose_name_plural': 'System Models'},
        ),
        migrations.AlterField(
            model_name='systemmodel',
            name='slug',
            field=models.SlugField(blank=True, primary_key=True, serialize=False),
        ),
    ]
