# Generated by Django 3.2.13 on 2022-08-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0003_alter_disklayout_slug'),
        ('systems', '0023_remove_system_bootdisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='bootdisk',
            field=models.ForeignKey(blank=True, help_text='Boot disk for stateful installs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='disklayouts.disklayout', verbose_name='Boot Disk'),
        ),
    ]
