# Generated by Django 3.2.13 on 2022-08-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0024_system_bootdisk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='bootdisk',
        ),
    ]
