# Generated by Django 3.2.13 on 2022-08-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disklayouts', '0006_auto_20220805_2040'),
        ('systems', '0026_system_disks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='disks',
            field=models.ManyToManyField(blank=True, to='disklayouts.DiskLayout'),
        ),
    ]
