# Generated by Django 3.2.15 on 2022-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0028_systembmc_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='initial_mods',
            field=models.CharField(default='e1000,tg3', help_text='Comma separated list of modules to load.', max_length=255),
        ),
        migrations.AddField(
            model_name='system',
            name='install_kernel_cmdline',
            field=models.CharField(blank=True, default='', help_text='Options to pass to the install kernel', max_length=4096),
        ),
        migrations.AddField(
            model_name='system',
            name='prov_interface',
            field=models.CharField(default='eth0', help_text='Interface name to provision over.', max_length=255),
        ),
        migrations.AddField(
            model_name='system',
            name='tmpfs_root_size',
            field=models.IntegerField(default=8, help_text='Size of the root tmpfs filesystem in Gibabytes'),
        ),
        migrations.AddField(
            model_name='systemgroup',
            name='initial_mods',
            field=models.CharField(default='e1000,tg3', help_text='Comma separated list of modules to load.', max_length=255),
        ),
        migrations.AddField(
            model_name='systemgroup',
            name='install_kernel_cmdline',
            field=models.CharField(blank=True, default='', help_text='Options to pass to the install kernel', max_length=4096),
        ),
        migrations.AddField(
            model_name='systemgroup',
            name='prov_interface',
            field=models.CharField(default='eth0', help_text='Interface name to provision over.', max_length=255),
        ),
        migrations.AddField(
            model_name='systemgroup',
            name='tmpfs_root_size',
            field=models.IntegerField(default=8, help_text='Size of the root tmpfs filesystem in Gibabytes'),
        ),
    ]
