# Generated by Django 3.2.15 on 2022-10-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0030_auto_20221017_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='initial_mods',
            field=models.CharField(blank=True, default='', help_text='Comma separated list of modules to load.', max_length=255),
        ),
        migrations.AlterField(
            model_name='system',
            name='prov_interface',
            field=models.CharField(blank=True, default='', help_text='Interface name to provision over.', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemgroup',
            name='initial_mods',
            field=models.CharField(blank=True, default='', help_text='Comma separated list of modules to load.', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemgroup',
            name='prov_interface',
            field=models.CharField(blank=True, default='', help_text='Interface name to provision over.', max_length=255),
        ),
    ]
