# Generated by Django 3.2.15 on 2022-10-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0016_alter_osdistro_options'),
        ('systems', '0031_auto_20221018_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='config_params',
            field=models.TextField(blank=True, default='# Inherit from System Group or Distribtion.', null=True, verbose_name='Configuration\nParameters'),
        ),
        migrations.AlterField(
            model_name='systemimage',
            name='config_params',
            field=models.TextField(blank=True, default='# Inherit from System Group or Distribtion.', null=True, verbose_name='Configuration\nParameters'),
        ),
        migrations.AlterField(
            model_name='systemimage',
            name='osdistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distro', to='osmanagement.osdistro', verbose_name='OS Distribution'),
        ),
    ]
