# Generated by Django 3.2.16 on 2022-11-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0032_auto_20221020_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='ipv6ll',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IPv6 LL Address'),
        ),
    ]
