# Generated by Django 3.2.16 on 2022-11-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0035_alter_networkinterface_duid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkinterface',
            name='duid',
        ),
    ]
