# Generated by Django 3.2.16 on 2022-11-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0037_networkinterface_ipv6gua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterface',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address '),
        ),
    ]
