# Generated by Django 3.2.16 on 2022-11-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0038_alter_networkinterface_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='systembmc',
            name='ipv6ll',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address '),
        ),
        migrations.AlterField(
            model_name='networkinterface',
            name='ipv6gua',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IPv6 SLAAC GUA'),
        ),
    ]
