# Generated by Django 3.2.16 on 2022-11-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0039_auto_20221115_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systembmc',
            name='ipv6ll',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IPv6 LL Address '),
        ),
    ]
