# Generated by Django 3.2.16 on 2023-01-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmanagement', '0017_osrepo_version'),
        ('systems', '0040_alter_systembmc_ipv6ll'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemgroup',
            name='systems',
            field=models.ManyToManyField(blank=True, to='systems.System'),
        ),
        migrations.AlterField(
            model_name='systemimage',
            name='osrepos',
            field=models.ManyToManyField(blank=True, to='osmanagement.OSRepo', verbose_name='Extra OS Repositories'),
        ),
    ]
