# Generated by Django 3.2.18 on 2023-03-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_auto_20230321_1939'),
        ('systems', '0041_auto_20230123_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='ansibleplaybooks',
            field=models.ManyToManyField(blank=True, to='scripts.AnsiblePlaybook'),
        ),
        migrations.AddField(
            model_name='systemimage',
            name='ansibleplaybooks',
            field=models.ManyToManyField(blank=True, to='scripts.AnsiblePlaybook'),
        ),
    ]
