# Generated by Django 3.2.18 on 2023-03-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_auto_20230321_1939'),
        ('systems', '0042_auto_20230328_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemgroup',
            name='ansibleplaybooks',
            field=models.ManyToManyField(blank=True, to='scripts.AnsiblePlaybook'),
        ),
    ]
