# Generated by Django 3.2.18 on 2023-04-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0010_alter_ansiblerole_roleurl'),
        ('systems', '0044_auto_20230403_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='ansibleroless',
            field=models.ManyToManyField(blank=True, to='scripts.AnsibleRole', verbose_name='Ansible Roles'),
        ),
        migrations.AddField(
            model_name='systemgroup',
            name='ansibleroles',
            field=models.ManyToManyField(blank=True, to='scripts.AnsibleRole', verbose_name='Ansible Roles'),
        ),
    ]
