# Generated by Django 3.2.18 on 2023-05-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0046_systemimage_ansibleroles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='ansibleroless',
            new_name='ansibleroles',
        ),
    ]
