# Generated by Django 3.2.20 on 2023-09-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0014_alter_switchport_networks'),
        ('systems', '0049_networkinterface_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterface',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.network', verbose_name='Network'),
        ),
    ]
