# Generated by Django 3.2.20 on 2023-09-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0050_alter_networkinterface_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='hostaliases',
            field=models.CharField(blank=True, help_text='A space separated list of alternate hostnames.', max_length=4096, null=True),
        ),
    ]
