# Generated by Django 3.2.23 on 2023-12-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0052_nadssystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemimage',
            name='customIPXE',
            field=models.TextField(blank=True, help_text='Leave blank to let mProv manage the image.  Entering text disables image building.', null=True, verbose_name='Custom IPXE Script'),
        ),
    ]
