# Generated by Django 3.2.22 on 2023-12-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0053_systemimage_customipxe'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='mtu',
            field=models.IntegerField(default=1500, verbose_name='MTU'),
        ),
    ]
