# Generated by Django 3.2.23 on 2024-01-23 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0054_networkinterface_mtu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nadssystem',
            name='discovered',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 3, 16, 43, 772310, tzinfo=utc), verbose_name='Discovered'),
        ),
        migrations.AlterField(
            model_name='system',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 3, 16, 43, 761968, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='system',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 3, 16, 43, 762028, tzinfo=utc), verbose_name='Lasted Updated'),
        ),
        migrations.AlterField(
            model_name='systemimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 3, 16, 43, 767477, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='systemimage',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 3, 16, 43, 767531, tzinfo=utc), verbose_name='Lasted Updated'),
        ),
    ]
