# Generated by Django 3.2.23 on 2024-01-23 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0055_auto_20240123_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nadssystem',
            name='discovered',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Discovered'),
        ),
        migrations.AlterField(
            model_name='system',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='system',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Lasted Updated'),
        ),
        migrations.AlterField(
            model_name='systemimage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='systemimage',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Lasted Updated'),
        ),
    ]
