# Generated by Django 3.2.23 on 2024-01-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0011_ansiblecollection'),
        ('systems', '0056_auto_20240123_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemimage',
            name='scripts',
            field=models.ManyToManyField(blank=True, default='install_mprov_script_runner_sh', to='scripts.Script'),
        ),
    ]
