# Generated by Django 3.2.23 on 2024-01-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0057_alter_systemimage_scripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='gateway',
            field=models.BooleanField(default=True, verbose_name='Gateway Nic?'),
        ),
    ]
