# Generated by Django 3.2.23 on 2024-01-31 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0058_networkinterface_gateway'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkinterface',
            old_name='gateway',
            new_name='isgateway',
        ),
    ]
