# Generated by Django 3.2.22 on 2025-01-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0060_auto_20240206_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='systembmc',
            name='vlan',
            field=models.IntegerField(default=0, verbose_name='VLAN ID'),
        ),
    ]
