# Generated by Django 3.2.18 on 2025-09-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0062_alter_networkinterface_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterface',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
