# Generated by Django 3.2.22 on 2026-02-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0063_alter_networkinterface_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='nadssystem',
            name='serial',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Serial Number'),
        ),
    ]
