# Generated by Django 3.2.18 on 2025-11-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0063_alter_networkinterface_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='provision',
            field=models.BooleanField(default=True, help_text='Should this system be provisioned?', verbose_name='Provision?'),
        ),
    ]
