# Generated by Django 4.2.30 on 2026-07-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0064_nadssystem_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLocation',
            fields=[
                ('slug', models.SlugField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Location ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('building', models.CharField(blank=True, max_length=1024, null=True)),
                ('room', models.CharField(blank=True, max_length=1024, null=True)),
                ('rack', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
