# Generated by Django 4.2.30 on 2026-07-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0065_systemlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.systemlocation'),
        ),
    ]
