name: Docker Image CI for Dev
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout 
        uses: actions/checkout@v2
      
      - 
        name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to GHCR
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - 
        name: Build Development Docker Image
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/mprov-ng/mprov-control-center-mariadb:dev
          push: true