name: Docker Image CI
on:
  release: 
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout 
        uses: actions/checkout@v2
      
      - 
        name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Parse the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - 
        name: Login to GHCR
        uses: docker/login-action@v1
        registry: ghcr.io
        with:
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - 
        name: Build the SQLite Docker Image
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/mprov-ng/mprov-control-center-sqlite:${{steps.vars.outputs.tag}}
            ghcr.io/mprov-ng/mprov-control-center-sqlite:latest
        push: true

      - 
        name: Build the MariaDB Docker Image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            MPROV_INSTALL_OPTS="-m"
          tags: |
            ghcr.io/mprov-ng/mprov-control-center-mariadb:${{steps.vars.outputs.tag}}
            ghcr.io/mprov-ng/mprov-control-center-mariadb:latest
        push: true

      - 
        name: Build the PostgreSQL DB Docker Image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            MPROV_INSTALL_OPTS="-p"
          tags: |
            ghcr.io/mprov-ng/mprov-control-center-pgsql:${{steps.vars.outputs.tag}}
            ghcr.io/mprov-ng/mprov-control-center-pgsql:latest
        push: true
